=== vakhariaheet/XML-Code/Chapter 3/Q05-Salesperson/Q05-Salesperson.xsd
<?xml version="1.0" encoding="UTF-8"?>
	
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="Salesperson">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Name"></xsd:element>
				<xsd:element name="BussinessInfo">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Company" type="xsd:string"></xsd:element>
							<xsd:element name="Department">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Sales"></xsd:enumeration>
										<xsd:enumeration value="Financial"></xsd:enumeration>
										<xsd:enumeration value="Operation"></xsd:enumeration>
										<xsd:enumeration value="Database"></xsd:enumeration>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Manager" type="xsd:string"></xsd:element>
							<xsd:element name="PhoneNo">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="10"></xsd:length>
									</xsd:restriction>							
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Email">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:pattern value="[\p{L}.]+@(\p{L}+\.)+[\p{L}-]{2,4}"></xsd:pattern>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="PersonalInfo">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="PhoneNo">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="10"></xsd:length>
									</xsd:restriction>							
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="Address" type="xsd:string"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== vakhariaheet/XML-Code/Chapter 3/Q05-Salesperson/Q05-Salesperson.xml
<?xml version="1.0" ?>
<Salesperson xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q05-Salesperson.xsd">
	<Name>John Doe</Name>
	<BussinessInfo>
		<Company>Heet</Company>
		<Department>Sales</Department>
		<Manager>John Doe</Manager>
		<PhoneNo>9104680032</PhoneNo>
		<Email>heet@heetvakharia.in</Email>
	</BussinessInfo>
	<PersonalInfo>
		<PhoneNo>9104680032</PhoneNo>
		<Address>Ahmedabad</Address>
	</PersonalInfo>
</Salesperson>
