=== vakhariaheet/XML-Code/Chapter 3/Q03-Student/Q03-Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
	
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="Student">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="StudentName" type="xsd:string"></xsd:element>
				<xsd:element name="PersonalInfo">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Address" type="xsd:string"></xsd:element>
							<xsd:element name="Birthdate" type="xsd:date"></xsd:element>
							<xsd:element name="Gender">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Male"></xsd:enumeration>
										<xsd:enumeration value="Female"></xsd:enumeration>
										<xsd:enumeration value="Other"></xsd:enumeration>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="MobileNo">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:maxLength value="10"></xsd:maxLength>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Result">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Total" type="xsd:double"></xsd:element>
							<xsd:element name="Percentage" type="xsd:float"></xsd:element>
							<xsd:element name="Grade" type="xsd:string"></xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== vakhariaheet/XML-Code/Chapter 3/Q03-Student/Q03-Student.xml
<?xml version="1.0"?>
<Student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q03-Student.xsd">
	<StudentName>John Doe</StudentName>
	<PersonalInfo>
		<Address>Ahmedabad</Address>
		<Birthdate>2005-02-05</Birthdate>
		<Gender>Male</Gender>
		<MobileNo>9104680032</MobileNo>
	</PersonalInfo>
	<Result>
		<Total>225</Total>
		<Percentage>80</Percentage>
		<Grade>A</Grade>
	</Result>
</Student>
